name: Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3

    - name: Add MSBuild to PATH
      uses: microsoft/setup-msbuild@v1.3.1
      env:
        ACTIONS_ALLOW_UNSECURE_COMMANDS: 'true'

    - name: Setup Nuget.exe
      uses: NuGet/setup-nuget@v1.2.0
      env:
        ACTIONS_ALLOW_UNSECURE_COMMANDS: 'true'

    - name: Restore packages
      run: nuget restore CustomerImport.sln

    - name: Install tools
      run: |
           dotnet restore
           dotnet tool restore

    - name: Install Coverlet
      run: dotnet tool install --global coverlet.console

    - name: Build Debug
      run: dotnet build --configuration Debug --no-restore CustomerImport.sln

    - name: Testing
      run: coverlet CustomerImport.UnitTests/bin/Debug/net472/CustomerImport.UnitTests.dll --target "dotnet" --targetargs "test CustomerImport.UnitTests/CustomerImport.UnitTests.csproj --no-build --verbosity quiet" --format OpenCover --output customerimport.coverage.xml

    - name: Upload coverage to CodeCov
      uses: codecov/codecov-action@v3.1.3

    - name: Archive code coverage results
      uses: actions/upload-artifact@v3
      with:
        name: code-coverage-report
        path: ./*.coverage.xml
